### ISSUE TITLE
Won't add custom attribute to pool

### ISSUE THREAD

**Issue by lsutton00** [mikeduminy/serverless-cognito-add-custom-attributes#6]
I don't get any error message, but the attribute isn't added to the pool:

Serverless: CognitoAddCustomAttributesPlugin: Start
Serverless: CognitoAddCustomAttributesPlugin: Found userPoolId: redacted
Serverless: CognitoAddCustomAttributesPlugin: End
Serverless: CognitoAddCustomAttributesPlugin: Found userPoolClientId: redacted
Serverless Enterprise: Run `serverless login` and deploy again to explore, monitor, secure your serverless project for free.

**Comment by michaelduminy** [comment]
Does the custom attribute already exist in the pool?

Can you paste relevant parts of your serverless file here?

**Comment by lsutton00** [comment]
No, the attribute definitely doesn't exist in the pool, the custom Attributes part of the yml is: 
`CognitoAddCustomAttributes:
    - CognitoUserPoolIdOutputKey: "UserPoolIdOutputKey"
      CognitoUserPoolClientIdOutputKey: "IdentityPoolIdOutputKey"
      CustomAttributes:
        - AttributeDataType: String
          DeveloperOnlyAttribute: False
          Mutable: True
          Name: "test"
          Required: False`

**Comment by scharles-resilient** [comment]
Same!
`  CognitoAddCustomAttributes:
    CognitoUserPoolIdOutputKey: "LimonUserPoolId"              # The key of the outputted UserPool Ref
    CognitoUserPoolClientIdOutputKey: "LimonUserPoolClientId"  # The key of the outputted UserPoolClient Ref
    CustomAttributes:
      -
        AttributeDataType: String
        DeveloperOnlyAttribute: False
        Mutable: True
        Name: "plugin-attribute" # this will end up being custom:another
        Required: False`
