### ISSUE TITLE
Make UserPoolClient optional

### ISSUE THREAD

**Issue by steveizzle** [mikeduminy/serverless-cognito-add-custom-attributes#9]
Hey guys, 
first, thx a lot for this cool plugin. For a project i am working on, we needed a solution for adding custom Attributes without loosing all current users, BUT without specifying an UserPoolClient. Because we needed this ASAP, i forked your project and realized it quick and maybe a little dirty. Could we also realize it in the original Plugin? I can create a PR, but i am not really a JS Dev. 
BR
Stefan

**Comment by jmaleonard** [comment]
Please send a PR, I am willing to have a look at it and even add functionality for you

**Comment by jmaleonard** [comment]
Merged
